### ISSUE TITLE
Gros problème

### ISSUE THREAD

**Issue by Sirbu** [Boneshield/ProjetJavaM1#1]
Le problème c'est que ça casse les couilles de faire tout le temps du java à la fac... ;)
T'es tout seul dessus ?

**Comment by Boneshield** [comment]
haha on peut presque dire ça ^^ c'est moi qui m'occupe de tout le code. Je leur laisse l'UML :)

**Comment by Sirbu** [comment]
Ah bah t'auras plus de taff, mais au moins ce sera intéressant !

**Comment by Boneshield** [comment]
J'ai pas mal progressé en java je trouve haha !
